# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ddc969d427e6254f5aeb82d20b4e36670e05ae909f58543a763e8e3af8566eac4b496512e1813ec7d1df93c85d64fdbd3b0820f5f8bf6a38242c0df465febcb

test:
  secret_key_base: ce5e383dccc5270b99517f4a8456880f631f42ddd9d0575ce8cd655ca5ba3c47d5eaf83e119d0c8b54cf263c6433ecbb35997cc8f42567fab0bc5d60446aa172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
